import type { Copy } from './types';

export const en: Copy = {
  lang: 'en',
  locale: 'en',
  langName: 'English',
  meta: {
    title: (brand, sub) => `${brand}${sub ? ` (${sub})` : ''} - horror quest with live actors in Chisinau`,
    description:
      'A horror quest with live actors in Chisinau. An old hotel that never closed, a host who never left, and 60 minutes to find the hidden key.',
    hiddenTitle: 'Your key is still here',
    ogAlt: 'Night facade of an old hotel with a red neon HOTEL sign',
  },
  ui: {
    skipToContent: 'Skip to content',
    skip: 'Skip',
    sound: 'Sound',
    soundOn: 'on',
    soundOff: 'off',
    book: 'Book',
    call: 'Call',
    askDesk: 'Ask the desk',
    languageNav: 'Language',
    preview: 'Preview version',
    whatsapp: 'Write on WhatsApp',
    waHello: (brand) => `Hello! I have a question about "${brand}".`,
    slots: 'See free slots',
  },
  places: {
    lobby: 'Lobby',
    corridor: 'Floor 3',
    archive: 'Archive',
    reception: 'Reception',
    cashier: 'Cashier',
    security: 'Security room',
    guestbook: 'Guest book',
    gift: 'Gift',
    registration: 'Registration',
    info: 'Information',
  },
  preloader: { label: 'Lift', floor: 'Floor' },
  hero: {
    kicker: ['Horror quest with live actors', 'Chisinau', '60 min'],
    line: 'We have been expecting you.',
    sub: 'An old hotel that never closed. A host who never left. One hour to find the key and learn why.',
    cta: 'Check in',
    tel: 'Call the front desk',
    hint: 'The lift only goes down',
    facadeAlt: 'Night facade of an old hotel. A red neon sign reads HOTEL, one letter is failing.',
  },
  corridor: {
    title: 'The corridor',
    captions: [
      'Third floor. The carpet swallows your steps.',
      'Someone is whispering behind the doors. Keep walking.',
      'The lights were fine a minute ago.',
      'Your room is the last one.',
    ],
    alt: 'A long hotel corridor with numbered doors. The ceiling lamps go out one by one.',
  },
  file: {
    title: 'The file',
    legend: [
      'The hotel opened in the late 1980s. One man built it and put everything he had into it: his money, his years, his name.',
      'Then his daughter died inside these walls. Nobody could explain how.',
      'He never shut the doors. He is still at the desk, and he greets every guest himself. Polite. Composed. He does not raise his voice.',
      'Guests talk about a child\'s silhouette at the far end of the corridor, and about whispers behind the doors of rooms that should be empty.',
      'Somewhere in the building there is a hidden key. Find it, and you will learn what keeps this family here.',
    ],
    registry: {
      caption: 'Guest registry',
      cols: { date: 'Date', guest: 'Guest', room: 'Room', out: 'Checked out' },
      rows: [
        { date: '03.09.1988', guest: 'Mr V., alone', room: '207' },
        { date: '21.11.1988', guest: 'The R. family', room: '311' },
        { date: '02.02.1989', guest: 'Mrs T. and daughter', room: '305' },
        { date: '17.05.1989', guest: 'Two guests, no names', room: '309' },
      ],
      you: 'You',
      note: 'The last column is empty on every page.',
    },
    clipping: {
      rubric: 'Incidents',
      year: '1989',
      headline: 'Girl dies in a city hotel. Cause not established',
      body: [
        'The owner\'s daughter was found inside the building late in the evening. Neither staff nor guests could say what happened.',
        'The hotel remains open. The owner declined to comment and went back to the front desk.',
      ],
      caption: 'Newspaper clipping, 1989',
    },
  },
  keys: {
    title: 'At the desk',
    intro: 'Four keys hang on the board. Take the one that is yours.',
    labels: { players: 'Players', duration: 'Duration', age: 'Age', price: 'Price' },
    duration: (m) => `${m} min`,
    priceFrom: (n, cur) => `from ${n} ${cur}`,
    limits: 'Live actors. Tell us your limits when you book.',
    level: {
      legend: 'Contact level',
      options: {
        light: {
          name: 'Light',
          text: 'The hotel keeps its distance. You came for the story, and the story is enough.',
        },
        standard: {
          name: 'Standard',
          text: 'The hotel behaves the way it always does. This is how most guests come to know it.',
        },
        hardcore: {
          name: 'Hardcore',
          text: 'The hotel stops being polite. Choose this only if everyone in your team agrees.',
        },
      },
      note: 'The exact contact rules for each level are confirmed by the desk when you book.',
    },
  },
  prices: {
    title: 'Price list',
    colTeam: 'Team',
    colPrice: 'Price',
    players: (a, b) => (a === b ? `${a} players` : `${a}-${b} players`),
    note: 'The price is for the whole team, in Moldovan lei (MDL).',
  },
  cctv: {
    title: 'Nobody is watching the monitors',
    sub: 'Four cameras. The tape runs all night.',
    cams: ['Lobby', 'Floor 3', 'Stairs', 'Basement'],
    rec: 'REC',
    alt: 'Security camera feed, static and a timestamp',
  },
  proof: {
    title: 'Those who checked out',
    outOf: 'out of 5',
    reviews: (n) => `${n} reviews`,
    source: 'Google rating',
    link: 'Read the reviews on Google Maps',
    review: 'Leave a review',
    quotesTitle: 'From the guest book',
  },
  voucher: {
    title: 'Gift voucher',
    text: 'Give someone a visit to the hotel. Choose the team size, write who it is for, and send us the request on WhatsApp.',
    team: 'Team size',
    recipient: "Recipient's name",
    submit: 'Request a voucher on WhatsApp',
    message: (d) => [`Hello! I would like a gift voucher for "${d.brand}".`, `Team size: ${d.team}`, `Recipient: ${d.recipient}`].join('\n'),
  },
  checkin: {
    title: 'Registration card',
    intro: 'Fill in the card. It opens WhatsApp with your booking request already written. Nothing is sent until you press send there.',
    cardNo: 'Card No.',
    fields: {
      date: 'Arrival date',
      time: 'Time',
      team: 'Guests',
      language: 'Language',
      level: 'Contact level',
      name: 'Name',
      phone: 'Phone',
      comment: 'Comment, your limits',
    },
    languages: { ro: 'Romanian', ru: 'Russian', en: 'English' },
    total: 'Total',
    submit: 'Send via WhatsApp',
    request: 'This is a booking request. We confirm it by a phone call.',
    tel: 'Or call',
    note: 'No payment on this page.',
    signature: 'Guest signature',
    message: (d) =>
      [
        `Hello! I would like to book "${d.brand}".`,
        `Date: ${d.date}`,
        `Time: ${d.time}`,
        `Guests: ${d.team}`,
        `Total: ${d.total}`,
        `Language: ${d.language}`,
        ...(d.level ? [`Contact level: ${d.level}`] : []),
        `Name: ${d.name}`,
        `Phone: ${d.phone}`,
        `Comment: ${d.comment}`,
      ].join('\n'),
  },
  faq: {
    title: 'Before you arrive',
    items: (v) => [
      {
        q: 'What is this?',
        a: `A horror quest with live actors in Chisinau. You are guests of an old hotel. You have ${v.minutes} minutes to find the hidden key and learn what binds the family to this place.`,
        known: true,
      },
      { q: 'How long does it last?', a: `${v.minutes} minutes.`, known: true },
      {
        q: 'How frightening is it?',
        a: v.levels
          ? 'You choose one of three contact levels: Light, Standard or Hardcore. Tell us which one when you book.'
          : 'It is a horror quest with live actors. Tell us your limits when you book.',
        known: true,
      },
      {
        q: 'Is there a minimum age?',
        a: v.age ? `Yes: ${v.age}.` : 'We are confirming this detail. Write or call and we will tell you.',
        known: Boolean(v.age),
      },
      {
        q: 'How many players can come?',
        a: `From ${v.players.min} to ${v.players.max} players. The minimum is ${v.players.min}.`,
        known: true,
      },
      {
        q: 'How much does it cost?',
        a: `${v.priceFrom[0].toUpperCase()}${v.priceFrom.slice(1)} per team. The price depends on the team size: see the price list on this page.`,
        known: true,
      },
      ...(v.vouchers
        ? [
            {
              q: 'How do I buy a gift voucher?',
              a: `Fill in the gift voucher block on this page: it opens WhatsApp with a ready request. Or call ${v.phone}.`,
              known: true,
            },
          ]
        : []),
      { q: 'What should I wear?', a: 'Light clothes in dark colours.', known: true },
      { q: 'Where are the rules explained?', a: 'On arrival, before the game starts.', known: true },
      {
        q: 'How can I pay?',
        a: v.payment ? v.payment : 'We are confirming this detail. Ask when you book.',
        known: Boolean(v.payment),
      },
      {
        q: 'How do I book?',
        a: `Fill in the registration card on this page: it opens WhatsApp with a ready booking request. We confirm the booking by a phone call. Or call ${v.phone}.`,
        known: true,
      },
      { q: 'Where is the hotel?', a: `${v.address}.`, known: true },
    ],
  },
  location: {
    title: 'How to find us',
    address: 'Address',
    hours: 'Hours',
    days: { 'mon-thu': 'Mon-Thu', fri: 'Fri', 'sat-sun': 'Sat-Sun' },
    allDay: '24 hours',
    phone: 'Front desk',
    directions: 'Directions in Google Maps',
  },
  footer: {
    hangerFront: 'Do not disturb',
    hangerBack: 'Too late',
    hangerHint: 'Turn the sign over',
    rights: 'All rights reserved.',
    top: 'Back to the lobby',
  },
  notFound: {
    title: 'There is no such room',
    text: 'This door does not open. Go back to the lobby.',
    back: 'To the lobby',
  },
};
