import type { Copy } from './types';

export const en: Copy = {
  lang: 'en',
  locale: 'en',
  langName: 'English',
  meta: {
    title: (brand) => `${brand} - horror quest with live actors in Chisinau`,
    description:
      'A horror quest with live actors in Chisinau. An old hotel that never closed, a host who never left, and 60 minutes to find the hidden key.',
    hiddenTitle: 'Your key is still here',
  },
  ui: {
    skipToContent: 'Skip to content',
    skip: 'Skip',
    sound: 'Sound',
    soundOn: 'on',
    soundOff: 'off',
    book: 'Book',
    call: 'Call',
    askDesk: 'Ask the desk',
    languageNav: 'Language',
    preview: 'Preview version',
  },
  places: {
    lobby: 'Lobby',
    corridor: 'Floor 3',
    archive: 'Archive',
    reception: 'Reception',
    security: 'Security room',
    guestbook: 'Guest book',
    registration: 'Registration',
    info: 'Information',
  },
  preloader: { label: 'Lift', floor: 'Floor' },
  hero: {
    kicker: ['Horror quest with live actors', 'Chisinau', '60 min'],
    line: 'We have been expecting you.',
    sub: 'An old hotel that never closed. A host who never left. One hour to find the key and learn why.',
    cta: 'Check in',
    tel: 'Call the front desk',
    hint: 'The lift only goes down',
    facadeAlt: 'Night facade of an old hotel. A red neon sign reads HOTEL, one letter is failing.',
  },
  corridor: {
    title: 'The corridor',
    captions: [
      'Third floor. The carpet swallows your steps.',
      'Someone is whispering behind the doors. Keep walking.',
      'The lights were fine a minute ago.',
      'Your room is the last one.',
    ],
    alt: 'A long hotel corridor with numbered doors. The ceiling lamps go out one by one.',
  },
  file: {
    title: 'The file',
    legend: [
      'The hotel opened in the late 1980s. One man built it and put everything he had into it: his money, his years, his name.',
      'Then his daughter died inside these walls. Nobody could explain how.',
      'He never shut the doors. He is still at the desk, and he greets every guest himself. Polite. Composed. He does not raise his voice.',
      'Guests talk about a child\'s silhouette at the far end of the corridor, and about whispers behind the doors of rooms that should be empty.',
      'Somewhere in the building there is a hidden key. Find it, and you will learn what keeps this family here.',
    ],
    registry: {
      caption: 'Guest registry',
      cols: { date: 'Date', guest: 'Guest', room: 'Room', out: 'Checked out' },
      rows: [
        { date: '03.09.1988', guest: 'Mr V., alone', room: '207' },
        { date: '21.11.1988', guest: 'The R. family', room: '311' },
        { date: '02.02.1989', guest: 'Mrs T. and daughter', room: '305' },
        { date: '17.05.1989', guest: 'Two guests, no names', room: '309' },
      ],
      you: 'You',
      note: 'The last column is empty on every page.',
    },
    clipping: {
      rubric: 'Incidents',
      year: '1989',
      headline: 'Girl dies in a city hotel. Cause not established',
      body: [
        'The owner\'s daughter was found inside the building late in the evening. Neither staff nor guests could say what happened.',
        'The hotel remains open. The owner declined to comment and went back to the front desk.',
      ],
      caption: 'Newspaper clipping, 1989',
    },
  },
  keys: {
    title: 'At the desk',
    intro: 'Four keys hang on the board. Take the one that is yours.',
    labels: { players: 'Players', duration: 'Duration', age: 'Age', price: 'Price' },
    duration: (m) => `${m} min`,
    level: {
      legend: 'Contact level',
      options: {
        light: {
          name: 'Light',
          text: 'The hotel keeps its distance. You came for the story, and the story is enough.',
        },
        standard: {
          name: 'Standard',
          text: 'The hotel behaves the way it always does. This is how most guests come to know it.',
        },
        hardcore: {
          name: 'Hardcore',
          text: 'The hotel stops being polite. Choose this only if everyone in your team agrees.',
        },
      },
      note: 'The exact contact rules for each level are confirmed by the desk when you book.',
    },
  },
  cctv: {
    title: 'Nobody is watching the monitors',
    sub: 'Four cameras. The tape runs all night.',
    cams: ['Lobby', 'Floor 3', 'Stairs', 'Basement'],
    rec: 'REC',
    alt: 'Security camera feed, static and a timestamp',
  },
  proof: {
    title: 'Those who checked out',
    outOf: 'out of 5',
    reviews: (n) => `${n} reviews`,
    source: 'Google rating',
    link: 'Read the reviews on Google Maps',
    quotesTitle: 'From the guest book',
  },
  checkin: {
    title: 'Registration card',
    intro: 'Fill in the card. It opens WhatsApp with your details already written. Nothing is sent until you press send there.',
    cardNo: 'Card No.',
    fields: {
      date: 'Arrival date',
      time: 'Time',
      team: 'Guests',
      language: 'Language',
      level: 'Contact level',
      name: 'Name',
      phone: 'Phone',
    },
    languages: { ro: 'Romanian', ru: 'Russian', en: 'English' },
    submit: 'Send via WhatsApp',
    tel: 'Or call',
    note: 'No payment on this page.',
    signature: 'Guest signature',
    message: (d) =>
      [
        `Hello! I would like to book "${d.brand}".`,
        `Date: ${d.date}`,
        `Time: ${d.time}`,
        `Guests: ${d.team}`,
        `Language: ${d.language}`,
        `Contact level: ${d.level}`,
        `Name: ${d.name}`,
        `Phone: ${d.phone}`,
      ].join('\n'),
  },
  faq: {
    title: 'Before you arrive',
    items: (v) => [
      {
        q: 'What is this?',
        a: `A horror quest with live actors in Chisinau. You are guests of an old hotel. You have ${v.minutes} minutes to find the hidden key and learn what binds the family to this place.`,
        known: true,
      },
      { q: 'How long does it last?', a: `${v.minutes} minutes.`, known: true },
      {
        q: 'How frightening is it?',
        a: 'You choose one of three contact levels: Light, Standard or Hardcore. Tell us which one when you book.',
        known: true,
      },
      {
        q: 'How many players can come?',
        a: v.players ? `Teams of ${v.players} players.` : 'We are confirming this detail. Write or call and we will tell you.',
        known: Boolean(v.players),
      },
      {
        q: 'Is there an age limit?',
        a: v.age ? `Yes: ${v.age}.` : 'We are confirming this detail. Write or call and we will tell you.',
        known: Boolean(v.age),
      },
      {
        q: 'How much does it cost?',
        a: v.price ? v.price : 'Ask for the current price when you book, on WhatsApp or by phone.',
        known: Boolean(v.price),
      },
      {
        q: 'How do I book?',
        a: `Fill in the registration card on this page: it opens WhatsApp with a ready message. Or call ${v.phone}.`,
        known: true,
      },
      { q: 'Where is the hotel?', a: `${v.address}.`, known: true },
    ],
  },
  location: {
    title: 'How to find us',
    address: 'Address',
    hours: 'Hours',
    hoursPlaceholder: 'Ask the desk by phone or on WhatsApp',
    phone: 'Front desk',
    directions: 'Directions in Google Maps',
  },
  footer: {
    hangerFront: 'Do not disturb',
    hangerBack: 'Too late',
    hangerHint: 'Turn the sign over',
    rights: 'All rights reserved.',
    top: 'Back to the lobby',
  },
  notFound: {
    title: 'There is no such room',
    text: 'This door does not open. Go back to the lobby.',
    back: 'To the lobby',
  },
};
