import type { Copy } from './types';

export const en: Copy = {
  lang: 'en',
  locale: 'en',
  langName: 'English',
  meta: {
    title: (brand, sub) => `${brand}${sub ? ` (${sub})` : ''} - horror quest with live actors in Chisinau`,
    description:
      'A horror quest with live actors in Chisinau. An old hotel that never closed, a host who never left, and 60 minutes to find the hidden key.',
    hiddenTitle: 'Your key is still here',
    ogAlt: 'Night facade of an old hotel with a red neon HOTEL sign',
  },
  ui: {
    skipToContent: 'Skip to content',
    skip: 'Skip',
    sound: 'Sound',
    soundOn: 'on',
    soundOff: 'off',
    book: 'Book',
    call: 'Call',
    languageNav: 'Language',
    preview: 'Preview version',
    whatsapp: 'Write on WhatsApp',
    waHello: (brand) => `Hello! I have a question about "${brand}".`,
    slots: 'See free slots',
    ask: 'Ask a question',
    telegram: 'Write on Telegram',
    toastTelegram: 'Message copied - paste it in Telegram',
    toastCopyFailed: 'Could not copy the message. Type it in Telegram.',
  },
  places: {
    lobby: 'Lobby',
    corridor: 'Floor 3',
    archive: 'Archive',
    reception: 'Reception',
    cashier: 'Cashier',
    security: 'Security room',
    guestbook: 'Guest book',
    gift: 'Gift',
    registration: 'Registration',
    info: 'Information',
  },
  preloader: { label: 'Lift', floor: 'Floor' },
  hero: {
    kicker: ['Horror quest with live actors', 'Chisinau', '60 min'],
    line: 'We have been expecting you.',
    sub: 'An old hotel that never closed. A host who never left. One hour to find the key and learn why.',
    cta: 'Check in',
    route: 'Directions',
    routeNote: 'Directions in Google Maps, opens in a new tab',
    tel: 'Call the front desk',
    hint: 'The lift only goes down',
    facadeAlt: 'Night facade of an old hotel in the rain. A red neon sign reads HOTEL: the letter E hangs from a single fixing and flickers.',
  },
  corridor: {
    title: 'The corridor',
    captions: [
      'Third floor. The carpet swallows your steps.',
      'Someone is whispering behind the doors. Keep walking.',
      'The lights were fine a minute ago.',
      'Your room is the last one.',
    ],
    alt: 'A long hotel corridor with numbered doors. The ceiling lamps go out one by one.',
  },
  file: {
    title: 'The file',
    legend: [
      'The hotel opened in the late 1980s. One man built it and put everything he had into it: his money, his years, his name.',
      'Then his daughter died inside these walls. Nobody could explain how.',
      'He never shut the doors. He is still at the desk, and he greets every guest himself. Polite. Composed. He does not raise his voice.',
      'Guests talk about a child\'s silhouette at the far end of the corridor, and about whispers behind the doors of rooms that should be empty.',
      'Somewhere in the building there is a hidden key. Find it, and you will learn what keeps this family here.',
    ],
    registry: {
      caption: 'Guest registry',
      cols: { date: 'Date', guest: 'Guest', room: 'Room', out: 'Checked out' },
      rows: [
        { date: '03.09.1988', guest: 'Mr V., alone', room: '207' },
        { date: '21.11.1988', guest: 'The R. family', room: '311' },
        { date: '02.02.1989', guest: 'Mrs T. and daughter', room: '305' },
        { date: '17.05.1989', guest: 'Two guests, no names', room: '309' },
      ],
      you: 'You',
      note: 'The last column is empty on every page.',
    },
    clipping: {
      rubric: 'Incidents',
      year: '1989',
      headline: 'Girl dies in a city hotel. Cause not established',
      body: [
        'The owner\'s daughter was found inside the building late in the evening. Neither staff nor guests could say what happened.',
        'The hotel remains open. The owner declined to comment and went back to the front desk.',
      ],
      caption: 'Newspaper clipping, 1989',
    },
  },
  keys: {
    title: 'At the desk',
    intro: 'Four keys hang on the board. Take the one that is yours.',
    labels: { players: 'Players', duration: 'Duration', age: 'Age', price: 'Price' },
    duration: (m) => `${m} min`,
    priceFrom: (n, cur) => `from ${n} ${cur}`,
    age: (min) => (min === null ? 'No age limit' : `${min}+`),
    ageNote: 'Agreement on arrival. Minors: a parent signs',
    level: {
      legend: 'Game level',
      options: { none: 'No electroshock', weak: 'Weak electroshock', hardcore: 'Hardcore' },
      note: 'The team chooses the level when booking.',
    },
  },
  prices: {
    title: 'Price list',
    colTeam: 'Team',
    colPrice: 'Price',
    players: (a, b) => (a === b ? `${a} players` : `${a}-${b} players`),
    note: 'The price is for the whole team, in Moldovan lei (MDL).',
  },
  cctv: {
    title: 'Nobody is watching the monitors',
    sub: 'Four cameras. The tape runs all night.',
    cams: ['Lobby', 'Floor 3', 'Stairs', 'Basement'],
    rec: 'REC',
    alt: 'Security camera feed, static and a timestamp',
  },
  proof: {
    title: 'Those who checked out',
    outOf: 'out of 5',
    reviews: (n) => `${n} reviews`,
    source: 'Google rating',
    link: 'Read the reviews on Google Maps',
    review: 'Leave a review',
    quotesTitle: 'From the guest book',
  },
  voucher: {
    title: 'Gift voucher',
    text: 'Give someone a visit to the hotel. Gift vouchers are bought at the venue, in cash.',
    where: 'Where to buy',
    whereValue: 'At the venue',
    pay: 'Payment',
    payValue: 'Cash',
    submit: 'Message us',
    message: (brand) => `Hello! I have a question about a gift voucher for "${brand}".`,
  },
  checkin: {
    title: 'Registration card',
    intro: 'Fill in the card, then choose a time. We copy one line with your details, and you paste it into the comment field of the booking form.',
    cardNo: 'Card No.',
    fields: { team: 'Guests', language: 'Language', level: 'Level' },
    languages: { ro: 'Romanian', ru: 'Russian', en: 'English' },
    total: 'Total',
    submit: 'Book a time slot',
    request: 'We copy one line: team, level, language, total. Paste it into the comment field of the booking form.',
    tel: 'Or call',
    note: 'No payment on this page. You pay in cash at the venue.',
    signature: 'Guest signature',
    summary: { team: 'Team', level: 'Level', language: 'Language', total: 'Total' },
    hello: (brand) => `Hello! I have a question about booking "${brand}".`,
  },
  booking: {
    title: 'Choose a time',
    copied: 'Copied',
    notCopied: 'Could not copy. Select the line and copy it yourself.',
    instruction: 'Paste this line into the comment field of the booking form.',
    copyAgain: 'Copy again',
    newTab: 'Open in a new tab',
    close: 'Close',
    frameTitle: 'EasyWeek booking form',
    slow: 'The booking form is taking a long time to load.',
  },
  faq: {
    title: 'Before you arrive',
    items: (v) => [
      {
        q: 'What is this?',
        a: `A horror quest with live actors in Chisinau. You are guests of an old hotel. You have ${v.minutes} minutes to find the hidden key and learn what binds the family to this place.`,
        known: true,
      },
      { q: 'How long does it last?', a: `${v.minutes} minutes.`, known: true },
      {
        q: 'How frightening is it?',
        a: v.levels
          ? 'It is a horror quest with live actors. There are three levels: No electroshock, Weak electroshock and Hardcore. The team chooses the level when booking.'
          : 'It is a horror quest with live actors.',
        known: true,
      },
      {
        q: 'Is there a minimum age?',
        a: `${v.minAge === null ? 'No, there is no age limit.' : `Yes: ${v.minAge}+.`} Everyone signs an agreement on arrival. Minors enter only if a parent signs it.`,
        known: true,
      },
      { q: 'What languages is the game played in?', a: 'Romanian, Russian or English. Choose the language on the registration card.', known: true },
      {
        q: 'How many players can come?',
        a: `From ${v.players.min} to ${v.players.max} players. The minimum is ${v.players.min}.`,
        known: true,
      },
      {
        q: 'How much does it cost?',
        a: `${v.priceFrom[0].toUpperCase()}${v.priceFrom.slice(1)} per team. The price depends on the team size: see the price list on this page.`,
        known: true,
      },
      ...(v.vouchers
        ? [
            {
              q: 'How do I buy a gift voucher?',
              a: `Gift vouchers are bought at the venue, in cash: ${v.address}. Questions? Write to us on WhatsApp or Telegram, or call ${v.phone}.`,
              known: true,
            },
          ]
        : []),
      { q: 'What should I wear?', a: 'Light clothes in dark colours.', known: true },
      { q: 'Where are the rules explained?', a: 'On arrival, before the game starts.', known: true },
      { q: 'How can I pay?', a: 'Cash only, at the venue.', known: true },
      {
        q: 'How do I book?',
        a: `Fill in the registration card on this page and press "Book a time slot". Choose a free time in the booking form and paste the copied line (team, level, language, total) into its comment field. Or call ${v.phone}.`,
        known: true,
      },
      { q: 'Where is the hotel?', a: `${v.address}.`, known: true },
    ],
  },
  location: {
    title: 'How to find us',
    address: 'Address',
    hours: 'Hours',
    days: { 'mon-thu': 'Mon-Thu', fri: 'Fri', 'sat-sun': 'Sat-Sun' },
    allDay: '24 hours',
    phone: 'Front desk',
    directions: 'Directions in Google Maps',
  },
  footer: {
    hangerFront: 'Do not disturb',
    hangerBack: 'Too late',
    hangerHint: 'Turn the sign over',
    rights: 'All rights reserved.',
    top: 'Back to the lobby',
  },
  notFound: {
    title: 'There is no such room',
    text: 'This door does not open. Go back to the lobby.',
    back: 'To the lobby',
  },
};
