import type { Copy } from './types';

export const ro: Copy = {
  lang: 'ro',
  locale: 'ro-MD',
  langName: 'Română',
  meta: {
    title: (brand, sub) => `${brand}${sub ? ` (${sub})` : ''} - quest horror cu actori, Chișinău`,
    description:
      'Quest horror cu actori în Chișinău. Un hotel vechi care nu s-a închis niciodată, o gazdă care nu a plecat și 60 de minute ca să găsiți cheia ascunsă.',
    hiddenTitle: 'Cheia vă așteaptă',
    ogAlt: 'Fațada unui hotel vechi, noaptea, cu o firmă roșie de neon: HOTEL',
  },
  ui: {
    skipToContent: 'Salt la conținut',
    skip: 'Omiteți',
    sound: 'Sunet',
    soundOn: 'pornit',
    soundOff: 'oprit',
    book: 'Rezervați',
    call: 'Sunați',
    askDesk: 'Întrebați recepția',
    languageNav: 'Limbă',
    preview: 'Versiune de previzualizare',
    whatsapp: 'Scrieți pe WhatsApp',
    waHello: (brand) => `Bună ziua! Am o întrebare despre „${brand}”.`,
    slots: 'Vedeți orele libere',
  },
  places: {
    lobby: 'Hol',
    corridor: 'Etajul 3',
    archive: 'Arhivă',
    reception: 'Recepție',
    cashier: 'Casierie',
    security: 'Camera de pază',
    guestbook: 'Cartea de oaspeți',
    gift: 'Cadou',
    registration: 'Cazare',
    info: 'Informații',
  },
  preloader: { label: 'Lift', floor: 'Etaj' },
  hero: {
    kicker: ['Quest horror cu actori', 'Chișinău', '60 min'],
    line: 'Vă așteptam.',
    sub: 'Un hotel vechi care nu s-a închis niciodată. O gazdă care nu a plecat. O oră ca să găsiți cheia și să aflați de ce.',
    cta: 'Check-in',
    route: 'Traseu',
    routeNote: 'Traseu în Google Maps, se deschide într-o filă nouă',
    tel: 'Sunați la recepție',
    hint: 'Liftul merge doar în jos',
    facadeAlt: 'Fațada unui hotel vechi, noaptea, pe ploaie. O firmă roșie de neon pe care scrie HOTEL: litera E atârnă într-un singur șurub și pâlpâie.',
  },
  corridor: {
    title: 'Coridorul',
    captions: [
      'Etajul trei. Covorul vă înghite pașii.',
      'În spatele ușilor se șoptește. Mergeți mai departe.',
      'Acum un minut, becurile încă mergeau.',
      'Camera dumneavoastră este ultima.',
    ],
    alt: 'Un coridor lung de hotel, cu uși numerotate. Lămpile din tavan se sting una câte una.',
  },
  file: {
    title: 'Dosarul',
    legend: [
      'Hotelul s-a deschis la sfârșitul anilor \'80. L-a ridicat un singur om, care a pus în el tot ce avea: banii, anii, numele.',
      'Apoi fiica lui a murit între acești pereți. Nimeni nu a putut explica cum.',
      'Nu a închis niciodată ușile. Este și acum la recepție și își întâmpină personal fiecare oaspete. Politicos. Stăpânit. Nu ridică vocea.',
      'Oaspeții vorbesc despre silueta unui copil la capătul coridorului și despre șoapte în spatele ușilor, în camere care ar trebui să fie goale.',
      'Undeva în clădire este ascunsă o cheie. Găsiți-o și veți afla ce ține această familie aici.',
    ],
    registry: {
      caption: 'Registrul de oaspeți',
      cols: { date: 'Data', guest: 'Oaspete', room: 'Camera', out: 'Plecare' },
      rows: [
        { date: '03.09.1988', guest: 'Dl V., singur', room: '207' },
        { date: '21.11.1988', guest: 'Familia R.', room: '311' },
        { date: '02.02.1989', guest: 'D-na T. cu fiica', room: '305' },
        { date: '17.05.1989', guest: 'Doi oaspeți, fără nume', room: '309' },
      ],
      you: 'Dumneavoastră',
      note: 'Ultima coloană este goală pe fiecare pagină.',
    },
    clipping: {
      rubric: 'Fapt divers',
      year: '1989',
      headline: 'O fetiță a murit într-un hotel din oraș. Cauza nu a fost stabilită',
      body: [
        'Fiica proprietarului a fost găsită în clădire seara târziu. Nici personalul, nici oaspeții nu au putut spune ce s-a întâmplat.',
        'Hotelul rămâne deschis. Proprietarul nu a dorit să comenteze și s-a întors la recepție.',
      ],
      caption: 'Tăietură din ziar, 1989',
    },
  },
  keys: {
    title: 'La recepție',
    intro: 'Pe panou atârnă patru chei. Luați-o pe a dumneavoastră.',
    labels: { players: 'Jucători', duration: 'Durată', age: 'Vârstă', price: 'Preț' },
    duration: (m) => `${m} min`,
    priceFrom: (n, cur) => `de la ${n} ${cur}`,
    limits: 'Actori reali. Spuneți-ne limitele dumneavoastră la rezervare.',
    level: {
      legend: 'Nivel de contact',
      options: {
        light: {
          name: 'Light',
          text: 'Hotelul păstrează distanța. Ați venit pentru poveste, iar povestea este de ajuns.',
        },
        standard: {
          name: 'Standard',
          text: 'Hotelul se poartă așa cum o face mereu. Așa îl cunosc cei mai mulți oaspeți.',
        },
        hardcore: {
          name: 'Hardcore',
          text: 'Hotelul nu mai este politicos. Alegeți acest nivel doar dacă toată echipa este de acord.',
        },
      },
      note: 'Regulile exacte de contact pentru fiecare nivel le confirmă recepția la rezervare.',
    },
  },
  prices: {
    title: 'Lista de prețuri',
    colTeam: 'Echipă',
    colPrice: 'Preț',
    players: (a, b) => (a === b ? `${a} jucători` : `${a}-${b} jucători`),
    note: 'Prețul este pentru întreaga echipă, în lei moldovenești (MDL).',
  },
  cctv: {
    title: 'Nimeni nu se uită la monitoare',
    sub: 'Patru camere. Banda merge toată noaptea.',
    cams: ['Hol', 'Etaj 3', 'Scară', 'Subsol'],
    rec: 'REC',
    alt: 'Imagine de la o cameră de supraveghere, cu purici și oră',
  },
  proof: {
    title: 'Cei care au plecat',
    outOf: 'din 5',
    reviews: (n) => `${n} de recenzii`,
    source: 'Rating Google',
    link: 'Citiți recenziile pe Google Maps',
    review: 'Lăsați o recenzie',
    quotesTitle: 'Din cartea de oaspeți',
  },
  voucher: {
    title: 'Voucher cadou',
    text: 'Dăruiți cuiva o vizită la hotel. Alegeți numărul de jucători, scrieți pentru cine este și trimiteți-ne cererea pe WhatsApp.',
    team: 'Număr de jucători',
    recipient: 'Numele destinatarului',
    submit: 'Cereți voucherul pe WhatsApp',
    message: (d) => [`Bună ziua! Aș dori un voucher cadou pentru „${d.brand}”.`, `Număr de jucători: ${d.team}`, `Destinatar: ${d.recipient}`].join('\n'),
  },
  checkin: {
    title: 'Fișă de cazare',
    intro: 'Completați fișa. Se deschide WhatsApp cu cererea de rezervare deja scrisă. Nimic nu se trimite până nu apăsați acolo pe trimitere.',
    cardNo: 'Fișa nr.',
    fields: {
      date: 'Data sosirii',
      time: 'Ora',
      team: 'Oaspeți',
      language: 'Limba',
      level: 'Nivel de contact',
      name: 'Nume',
      phone: 'Telefon',
      comment: 'Comentariu, limitele dumneavoastră',
    },
    languages: { ro: 'Română', ru: 'Rusă', en: 'Engleză' },
    total: 'Total',
    submit: 'Trimiteți pe WhatsApp',
    request: 'Aceasta este o cerere de rezervare. O confirmăm printr-un apel telefonic.',
    tel: 'Sau sunați',
    note: 'Nicio plată pe această pagină.',
    signature: 'Semnătura oaspetelui',
    message: (d) =>
      [
        `Bună ziua! Aș dori să rezerv „${d.brand}”.`,
        `Data: ${d.date}`,
        `Ora: ${d.time}`,
        `Oaspeți: ${d.team}`,
        `Total: ${d.total}`,
        `Limba: ${d.language}`,
        ...(d.level ? [`Nivel de contact: ${d.level}`] : []),
        `Nume: ${d.name}`,
        `Telefon: ${d.phone}`,
        `Comentariu: ${d.comment}`,
      ].join('\n'),
  },
  faq: {
    title: 'Înainte să ajungeți',
    items: (v) => [
      {
        q: 'Ce este acest loc?',
        a: `Un quest horror cu actori, în Chișinău. Sunteți oaspeții unui hotel vechi. Aveți ${v.minutes} de minute ca să găsiți cheia ascunsă și să aflați ce leagă familia de acest loc.`,
        known: true,
      },
      { q: 'Cât durează?', a: `${v.minutes} de minute.`, known: true },
      {
        q: 'Cât de înfricoșător este?',
        a: v.levels
          ? 'Alegeți unul dintre cele trei niveluri de contact: Light, Standard sau Hardcore. Spuneți-ne nivelul la rezervare.'
          : 'Este un quest horror cu actori. Spuneți-ne limitele dumneavoastră la rezervare.',
        known: true,
      },
      {
        q: 'Există o vârstă minimă?',
        a: v.age ? `Da: ${v.age}.` : 'Confirmăm acest detaliu. Scrieți-ne sau sunați și vă spunem.',
        known: Boolean(v.age),
      },
      {
        q: 'Câți jucători pot veni?',
        a: `De la ${v.players.min} la ${v.players.max} jucători. Minimum ${v.players.min}.`,
        known: true,
      },
      {
        q: 'Cât costă?',
        a: `${v.priceFrom[0].toUpperCase()}${v.priceFrom.slice(1)} pentru echipă. Prețul depinde de numărul de jucători: vedeți lista de prețuri de pe această pagină.`,
        known: true,
      },
      ...(v.vouchers
        ? [
            {
              q: 'Cum cumpăr un voucher cadou?',
              a: `Completați blocul „Voucher cadou” de pe această pagină: se deschide WhatsApp cu cererea gata scrisă. Sau sunați la ${v.phone}.`,
              known: true,
            },
          ]
        : []),
      { q: 'Cum să mă îmbrac?', a: 'Haine ușoare, de culoare închisă.', known: true },
      { q: 'Unde se explică regulile?', a: 'La sosire, înainte de începerea jocului.', known: true },
      {
        q: 'Cum pot plăti?',
        a: v.payment ? v.payment : 'Confirmăm acest detaliu. Întrebați la rezervare.',
        known: Boolean(v.payment),
      },
      {
        q: 'Cum rezerv?',
        a: `Completați fișa de cazare de pe această pagină: se deschide WhatsApp cu cererea de rezervare gata scrisă. Confirmăm rezervarea printr-un apel telefonic. Sau sunați la ${v.phone}.`,
        known: true,
      },
      { q: 'Unde este hotelul?', a: `${v.address}.`, known: true },
    ],
  },
  location: {
    title: 'Cum ne găsiți',
    address: 'Adresă',
    hours: 'Program',
    days: { 'mon-thu': 'Luni-Joi', fri: 'Vineri', 'sat-sun': 'Sâmbătă-Duminică' },
    allDay: 'non-stop',
    phone: 'Recepție',
    directions: 'Traseu în Google Maps',
  },
  footer: {
    hangerFront: 'Nu deranjați',
    hangerBack: 'Prea târziu',
    hangerHint: 'Întoarceți cartonașul',
    rights: 'Toate drepturile rezervate.',
    top: 'Înapoi în hol',
  },
  notFound: {
    title: 'Nu există o asemenea cameră',
    text: 'Ușa aceasta nu se deschide. Întoarceți-vă în hol.',
    back: 'Spre hol',
  },
};
