import type { Copy } from './types';

export const ro: Copy = {
  lang: 'ro',
  locale: 'ro-MD',
  langName: 'Română',
  meta: {
    title: (brand, sub) => `${brand}${sub ? ` (${sub})` : ''} - quest horror cu actori, Chișinău`,
    description: (m) =>
      `Quest horror cu actori în Chișinău. Un hotel vechi care nu s-a închis niciodată, o gazdă care nu a plecat și ${m} de minute ca să găsiți cheia ascunsă.`,
    hiddenTitle: 'Cheia vă așteaptă',
    ogAlt: 'Fațada unui hotel vechi, noaptea, cu o firmă roșie de neon: HOTEL',
  },
  ui: {
    skipToContent: 'Salt la conținut',
    skip: 'Omiteți',
    sound: 'Sunet',
    soundOn: 'pornit',
    soundOff: 'oprit',
    book: 'Rezervați',
    call: 'Sunați',
    languageNav: 'Limbă',
    preview: 'Versiune de previzualizare',
    whatsapp: 'Scrieți pe WhatsApp',
    waHello: (brand) => `Bună ziua! Am o întrebare despre „${brand}”.`,
    ask: 'Puneți o întrebare',
    telegram: 'Scrieți pe Telegram',
    toastTelegram: 'Mesaj copiat - lipiți-l în Telegram',
    toastCopyFailed: 'Mesajul nu a putut fi copiat. Scrieți-l în Telegram.',
  },
  places: {
    lobby: 'Hol',
    corridor: 'Etajul 3',
    archive: 'Arhivă',
    reception: 'Recepție',
    cashier: 'Casierie',
    security: 'Camera de pază',
    guestbook: 'Cartea de oaspeți',
    gift: 'Cadou',
    registration: 'Cazare',
    info: 'Informații',
  },
  preloader: { label: 'Lift', floor: 'Etaj' },
  hero: {
    kicker: ['Quest horror cu actori', 'Chișinău'],
    line: 'Vă așteptam.',
    sub: 'Un hotel vechi care nu s-a închis niciodată. O gazdă care nu a plecat. O oră sau mai mult ca să găsiți cheia și să aflați de ce.',
    cta: 'Check-in',
    route: 'Traseu',
    routeNote: 'Traseu în Google Maps, se deschide într-o filă nouă',
    tel: 'Sunați la recepție',
    hint: 'Liftul merge doar în jos',
    facadeAlt: 'Fațada unui hotel vechi, noaptea, pe ploaie. O firmă roșie de neon pe care scrie HOTEL: litera E atârnă într-un singur șurub și pâlpâie.',
  },
  corridor: {
    title: 'Coridorul',
    captions: [
      'Etajul trei. Covorul vă înghite pașii.',
      'În spatele ușilor se șoptește. Mergeți mai departe.',
      'Acum un minut, becurile încă mergeau.',
      'Camera dumneavoastră este ultima.',
    ],
    alt: 'Un drum la lumina lanternei pe un coridor întunecat de hotel, cu uși numerotate, până la camera 313.',
  },
  file: {
    title: 'Dosarul',
    legend: [
      'Hotelul s-a deschis la sfârșitul anilor \'80. L-a ridicat un singur om, care a pus în el tot ce avea: banii, anii, numele.',
      'Apoi fiica lui a murit între acești pereți. Nimeni nu a putut explica cum.',
      'Nu a închis niciodată ușile. Este și acum la recepție și își întâmpină personal fiecare oaspete. Politicos. Stăpânit. Nu ridică vocea.',
      'Oaspeții vorbesc despre silueta unui copil la capătul coridorului și despre șoapte în spatele ușilor, în camere care ar trebui să fie goale.',
      'Undeva în clădire este ascunsă o cheie. Găsiți-o și veți afla ce ține această familie aici.',
    ],
    registry: {
      caption: 'Registrul de oaspeți',
      cols: { date: 'Data', guest: 'Oaspete', room: 'Camera', out: 'Plecare' },
      rows: [
        { date: '03.09.1988', guest: 'Dl V., singur', room: '207' },
        { date: '21.11.1988', guest: 'Familia R.', room: '311' },
        { date: '02.02.1989', guest: 'D-na T. cu fiica', room: '305' },
        { date: '17.05.1989', guest: 'Doi oaspeți, fără nume', room: '309' },
      ],
      you: 'Dumneavoastră',
      note: 'Ultima coloană este goală pe fiecare pagină.',
    },
    clipping: {
      rubric: 'Fapt divers',
      year: '1989',
      headline: 'O fetiță a murit într-un hotel din oraș. Cauza nu a fost stabilită',
      body: [
        'Fiica proprietarului a fost găsită în clădire seara târziu. Nici personalul, nici oaspeții nu au putut spune ce s-a întâmplat.',
        'Hotelul rămâne deschis. Proprietarul nu a dorit să comenteze și s-a întors la recepție.',
      ],
      caption: 'Tăietură din ziar, 1989',
    },
  },
  keys: {
    title: 'La recepție',
    intro: 'Pe panou atârnă patru chei. Luați-o pe a dumneavoastră.',
    labels: { players: 'Jucători', duration: 'Durată', age: 'Vârstă', price: 'Preț' },
    duration: (m) => `${m} min`,
    priceFrom: (n, cur) => `de la ${n} ${cur}`,
    age: (min) => (min === null ? 'Fără limită' : `${min}+`),
    ageNote: 'Acord la sosire. Minori: semnează un părinte, fără electroșoc',
    level: {
      legend: 'Nivelul jocului',
      options: { none: 'Fără electroșoc', hardcore: 'Hardcore' },
      note: 'Echipa alege nivelul la rezervare.',
      minors: 'Echipele cu minori joacă fără electroșoc.',
    },
  },
  prices: {
    title: 'Lista de prețuri',
    colTeam: 'Echipă',
    colPrice: 'Preț',
    players: (a, b) => (a === b ? `${a} jucători` : `${a}-${b} jucători`),
    note: 'Prețul este pentru întreaga echipă, în lei moldovenești (MDL).',
  },
  cctv: {
    title: 'Nimeni nu se uită la monitoare',
    sub: 'Patru camere. Banda merge toată noaptea.',
    cams: ['Hol', 'Etaj 3', 'Scară', 'Subsol'],
    rec: 'REC',
    alt: 'Imagine de la o cameră de supraveghere, cu purici și oră',
  },
  proof: {
    title: 'Cei care au plecat',
    outOf: 'din 5',
    reviews: (n) => `${n} de recenzii`,
    source: 'Rating Google',
    link: 'Citiți toate recenziile pe Google',
    review: 'Lăsați o recenzie',
    quotesTitle: 'Din cartea de oaspeți',
    translatedFrom: { ru: 'tradus din rusă', en: 'tradus din engleză' },
  },
  voucher: {
    title: 'Voucher cadou',
    text: 'Dăruiți cuiva o vizită la hotel. Voucherul cadou se cumpără la fața locului, în numerar.',
    where: 'De unde se cumpără',
    whereValue: 'La fața locului',
    pay: 'Plata',
    payValue: 'Numerar',
    submit: 'Scrieți-ne',
    message: (brand) => `Bună ziua! Am o întrebare despre un voucher cadou pentru „${brand}”.`,
  },
  checkin: {
    title: 'Fișă de cazare',
    intro: 'Completați fișa, apoi alegeți ora. Noi copiem un rând cu datele dumneavoastră, iar dumneavoastră îl lipiți în câmpul de comentariu al formularului de rezervare.',
    cardNo: 'Fișa nr.',
    fields: { team: 'Oaspeți', language: 'Limba', level: 'Nivel' },
    languages: { ro: 'Română', ru: 'Rusă', en: 'Engleză' },
    total: 'Total',
    submit: 'Rezervați o oră',
    choose: (levels) => (levels ? 'Alegeți mărimea echipei și nivelul' : 'Alegeți mărimea echipei'),
    confirmCall: 'Vă sunăm în ziua jocului pentru a confirma rezervarea.',
    request: 'Copiem un singur rând: echipă, nivel, limbă, total. Lipiți-l în câmpul de comentariu al formularului de rezervare.',
    tel: 'Sau sunați',
    note: 'Nicio plată pe această pagină. Plata se face în numerar, la fața locului.',
    signature: 'Semnătura oaspetelui',
    summary: { team: 'Echipă', level: 'Nivel', language: 'Limbă', total: 'Total' },
    hello: (brand) => `Bună ziua! Am o întrebare despre rezervarea la „${brand}”.`,
  },
  booking: {
    title: 'Alegeți ora',
    copied: 'Copiat',
    notCopied: 'Nu am putut copia. Selectați rândul și copiați-l manual.',
    instruction: 'Lipiți acest rând în câmpul de comentariu al formularului de rezervare.',
    copyAgain: 'Copiați din nou',
    newTab: 'Deschideți într-o filă nouă',
    close: 'Închideți',
    frameTitle: 'Formular de rezervare EasyWeek',
    slow: 'Formularul de rezervare se încarcă prea încet.',
  },
  faq: {
    title: 'Înainte să ajungeți',
    items: (v) => [
      {
        q: 'Ce este acest loc?',
        a: `Un quest horror cu actori, în Chișinău. Sunteți oaspeții unui hotel vechi. Aveți ${v.minutes} de minute ca să găsiți cheia ascunsă și să aflați ce leagă familia de acest loc.`,
        known: true,
      },
      { q: 'Cât durează?', a: `${v.minutes} de minute.`, known: true },
      {
        q: 'Cât de înfricoșător este?',
        a: v.levels
          ? 'Este un quest horror cu actori. Există două niveluri: Fără electroșoc și Hardcore. Echipa alege nivelul la rezervare.'
          : 'Este un quest horror cu actori.',
        known: true,
      },
      {
        q: 'Există o vârstă minimă?',
        a: `${v.minAge === null ? 'Nu, nu există limită de vârstă.' : `Da: ${v.minAge}+.`} Toți participanții semnează un acord la sosire. Minorii intră doar dacă acordul este semnat de un părinte. Echipele cu minori joacă fără electroșoc.`,
        known: true,
      },
      { q: 'În ce limbi se joacă?', a: 'În română, rusă sau engleză. Alegeți limba în fișa de cazare.', known: true },
      {
        q: 'Câți jucători pot veni?',
        a: `De la ${v.players.min} la ${v.players.max} jucători. Minimum ${v.players.min}.`,
        known: true,
      },
      {
        q: 'Cât costă?',
        a: `${v.priceFrom[0].toUpperCase()}${v.priceFrom.slice(1)} pentru echipă. Prețul depinde de numărul de jucători: vedeți lista de prețuri de pe această pagină.`,
        known: true,
      },
      ...(v.vouchers
        ? [
            {
              q: 'Cum cumpăr un voucher cadou?',
              a: `Voucherul cadou se cumpără la fața locului, în numerar: ${v.address}. Aveți întrebări? Scrieți-ne pe WhatsApp sau pe Telegram ori sunați la ${v.phone}.`,
              known: true,
            },
          ]
        : []),
      { q: 'Cum să mă îmbrac?', a: 'Haine ușoare, de culoare închisă.', known: true },
      { q: 'Unde se explică regulile?', a: 'La sosire, înainte de începerea jocului.', known: true },
      { q: 'Cum pot plăti?', a: 'Doar în numerar, la fața locului.', known: true },
      {
        q: 'Cum rezerv?',
        a: `Completați fișa de cazare de pe această pagină și apăsați „Rezervați o oră”. Alegeți o oră liberă în formularul de rezervare și lipiți rândul copiat (echipă, nivel, limbă, total) în câmpul de comentariu. Sau sunați la ${v.phone}.${v.confirmCall ? ` ${v.confirmCall}` : ''}`,
        known: true,
      },
      { q: 'Unde este hotelul?', a: `${v.address}.`, known: true },
    ],
  },
  location: {
    title: 'Cum ne găsiți',
    address: 'Adresă',
    hours: 'Program',
    days: { 'mon-thu': 'Luni-Joi', fri: 'Vineri', 'sat-sun': 'Sâmbătă-Duminică' },
    allDay: 'non-stop',
    phone: 'Recepție',
    directions: 'Traseu în Google Maps',
  },
  footer: {
    hangerFront: 'Nu deranjați',
    hangerBack: 'Prea târziu',
    hangerHint: 'Întoarceți cartonașul',
    rights: 'Toate drepturile rezervate.',
    top: 'Înapoi în hol',
  },
  notFound: {
    title: 'Nu există o asemenea cameră',
    text: 'Ușa aceasta nu se deschide. Întoarceți-vă în hol.',
    back: 'Spre hol',
  },
};
