import type { Copy } from './types';

export const ro: Copy = {
  lang: 'ro',
  locale: 'ro-MD',
  langName: 'Română',
  meta: {
    title: (brand) => `${brand} - quest horror cu actori, Chișinău`,
    description:
      'Quest horror cu actori în Chișinău. Un hotel vechi care nu s-a închis niciodată, o gazdă care nu a plecat și 60 de minute ca să găsiți cheia ascunsă.',
    hiddenTitle: 'Cheia vă așteaptă',
  },
  ui: {
    skipToContent: 'Sari la conținut',
    skip: 'Omite',
    sound: 'Sunet',
    soundOn: 'pornit',
    soundOff: 'oprit',
    book: 'Rezervați',
    call: 'Sunați',
    askDesk: 'Întrebați recepția',
    languageNav: 'Limbă',
    preview: 'Versiune de previzualizare',
  },
  places: {
    lobby: 'Hol',
    corridor: 'Etajul 3',
    archive: 'Arhivă',
    reception: 'Recepție',
    security: 'Camera de pază',
    guestbook: 'Cartea de oaspeți',
    registration: 'Cazare',
    info: 'Informații',
  },
  preloader: { label: 'Lift', floor: 'Etaj' },
  hero: {
    kicker: ['Quest horror cu actori', 'Chișinău', '60 min'],
    line: 'Vă așteptam.',
    sub: 'Un hotel vechi care nu s-a închis niciodată. O gazdă care nu a plecat. O oră ca să găsiți cheia și să aflați de ce.',
    cta: 'Check-in',
    tel: 'Sunați la recepție',
    hint: 'Liftul merge doar în jos',
    facadeAlt: 'Fațada unui hotel vechi, noaptea. O firmă roșie de neon pe care scrie HOTEL, cu o literă care se stinge.',
  },
  corridor: {
    title: 'Coridorul',
    captions: [
      'Etajul trei. Covorul vă înghite pașii.',
      'În spatele ușilor se șoptește. Mergeți mai departe.',
      'Acum un minut, becurile încă mergeau.',
      'Camera dumneavoastră este ultima.',
    ],
    alt: 'Un coridor lung de hotel, cu uși numerotate. Lămpile din tavan se sting una câte una.',
  },
  file: {
    title: 'Dosarul',
    legend: [
      'Hotelul s-a deschis la sfârșitul anilor \'80. L-a ridicat un singur om, care a pus în el tot ce avea: banii, anii, numele.',
      'Apoi fiica lui a murit între acești pereți. Nimeni nu a putut explica cum.',
      'Nu a închis niciodată ușile. Este și acum la recepție și își întâmpină personal fiecare oaspete. Politicos. Stăpânit. Nu ridică vocea.',
      'Oaspeții vorbesc despre silueta unui copil la capătul coridorului și despre șoapte în spatele ușilor, în camere care ar trebui să fie goale.',
      'Undeva în clădire este ascunsă o cheie. Găsiți-o și veți afla ce ține această familie aici.',
    ],
    registry: {
      caption: 'Registrul de oaspeți',
      cols: { date: 'Data', guest: 'Oaspete', room: 'Camera', out: 'Plecare' },
      rows: [
        { date: '03.09.1988', guest: 'Dl V., singur', room: '207' },
        { date: '21.11.1988', guest: 'Familia R.', room: '311' },
        { date: '02.02.1989', guest: 'D-na T. cu fiica', room: '305' },
        { date: '17.05.1989', guest: 'Doi oaspeți, fără nume', room: '309' },
      ],
      you: 'Dumneavoastră',
      note: 'Ultima coloană este goală pe fiecare pagină.',
    },
    clipping: {
      rubric: 'Fapt divers',
      year: '1989',
      headline: 'O fetiță a murit într-un hotel din oraș. Cauza nu a fost stabilită',
      body: [
        'Fiica proprietarului a fost găsită în clădire seara târziu. Nici personalul, nici oaspeții nu au putut spune ce s-a întâmplat.',
        'Hotelul rămâne deschis. Proprietarul nu a dorit să comenteze și s-a întors la recepție.',
      ],
      caption: 'Tăietură din ziar, 1989',
    },
  },
  keys: {
    title: 'La recepție',
    intro: 'Pe panou atârnă patru chei. Luați-o pe a dumneavoastră.',
    labels: { players: 'Jucători', duration: 'Durată', age: 'Vârstă', price: 'Preț' },
    duration: (m) => `${m} min`,
    level: {
      legend: 'Nivel de contact',
      options: {
        light: {
          name: 'Light',
          text: 'Hotelul păstrează distanța. Ați venit pentru poveste, iar povestea este de ajuns.',
        },
        standard: {
          name: 'Standard',
          text: 'Hotelul se poartă așa cum o face mereu. Așa îl cunosc cei mai mulți oaspeți.',
        },
        hardcore: {
          name: 'Hardcore',
          text: 'Hotelul nu mai este politicos. Alegeți acest nivel doar dacă toată echipa este de acord.',
        },
      },
      note: 'Regulile exacte de contact pentru fiecare nivel le confirmă recepția la rezervare.',
    },
  },
  cctv: {
    title: 'Nimeni nu se uită la monitoare',
    sub: 'Patru camere. Banda merge toată noaptea.',
    cams: ['Hol', 'Etaj 3', 'Scară', 'Subsol'],
    rec: 'REC',
    alt: 'Imagine de la o cameră de supraveghere, cu purici și oră',
  },
  proof: {
    title: 'Cei care au plecat',
    outOf: 'din 5',
    reviews: (n) => `${n} de recenzii`,
    source: 'Rating Google',
    link: 'Citiți recenziile pe Google Maps',
    quotesTitle: 'Din cartea de oaspeți',
  },
  checkin: {
    title: 'Fișă de cazare',
    intro: 'Completați fișa. Se deschide WhatsApp cu datele dumneavoastră deja scrise. Nimic nu se trimite până nu apăsați acolo pe trimitere.',
    cardNo: 'Fișa nr.',
    fields: {
      date: 'Data sosirii',
      time: 'Ora',
      team: 'Oaspeți',
      language: 'Limba',
      level: 'Nivel de contact',
      name: 'Nume',
      phone: 'Telefon',
    },
    languages: { ro: 'Română', ru: 'Rusă', en: 'Engleză' },
    submit: 'Trimiteți pe WhatsApp',
    tel: 'Sau sunați',
    note: 'Nicio plată pe această pagină.',
    signature: 'Semnătura oaspetelui',
    message: (d) =>
      [
        `Bună ziua! Aș dori să rezerv „${d.brand}”.`,
        `Data: ${d.date}`,
        `Ora: ${d.time}`,
        `Oaspeți: ${d.team}`,
        `Limba: ${d.language}`,
        `Nivel de contact: ${d.level}`,
        `Nume: ${d.name}`,
        `Telefon: ${d.phone}`,
      ].join('\n'),
  },
  faq: {
    title: 'Înainte să ajungeți',
    items: (v) => [
      {
        q: 'Ce este acest loc?',
        a: `Un quest horror cu actori, în Chișinău. Sunteți oaspeții unui hotel vechi. Aveți ${v.minutes} de minute ca să găsiți cheia ascunsă și să aflați ce leagă familia de acest loc.`,
        known: true,
      },
      { q: 'Cât durează?', a: `${v.minutes} de minute.`, known: true },
      {
        q: 'Cât de înfricoșător este?',
        a: 'Alegeți unul dintre cele trei niveluri de contact: Light, Standard sau Hardcore. Spuneți-ne nivelul la rezervare.',
        known: true,
      },
      {
        q: 'Câți jucători pot veni?',
        a: v.players ? `Echipe de ${v.players} jucători.` : 'Confirmăm acest detaliu. Scrieți-ne sau sunați și vă spunem.',
        known: Boolean(v.players),
      },
      {
        q: 'Există o limită de vârstă?',
        a: v.age ? `Da: ${v.age}.` : 'Confirmăm acest detaliu. Scrieți-ne sau sunați și vă spunem.',
        known: Boolean(v.age),
      },
      {
        q: 'Cât costă?',
        a: v.price ? v.price : 'Întrebați prețul actual la rezervare, pe WhatsApp sau la telefon.',
        known: Boolean(v.price),
      },
      {
        q: 'Cum rezerv?',
        a: `Completați fișa de cazare de pe această pagină: se deschide WhatsApp cu mesajul gata scris. Sau sunați la ${v.phone}.`,
        known: true,
      },
      { q: 'Unde este hotelul?', a: `${v.address}.`, known: true },
    ],
  },
  location: {
    title: 'Cum ne găsiți',
    address: 'Adresă',
    hours: 'Program',
    hoursPlaceholder: 'Întrebați recepția la telefon sau pe WhatsApp',
    phone: 'Recepție',
    directions: 'Traseu în Google Maps',
  },
  footer: {
    hangerFront: 'Nu deranjați',
    hangerBack: 'Prea târziu',
    hangerHint: 'Întoarceți cartonașul',
    rights: 'Toate drepturile rezervate.',
    top: 'Înapoi în hol',
  },
  notFound: {
    title: 'Nu există o asemenea cameră',
    text: 'Ușa aceasta nu se deschide. Întoarceți-vă în hol.',
    back: 'Spre hol',
  },
};
